services:
  postgres:
    image: postgres:15
    container_name: postgres-1
    restart: always
    environment:
      POSTGRES_USER: rck
      POSTGRES_PASSWORD: krc123
      POSTGRES_DB: rck_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: ./api
    container_name: api-1
    env_file:
      - ./.env
    command: ["./wait-for-postgres.sh", "postgres", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  nginx:
    image: nginx:stable
    container_name: nginx-1
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

  prometheus:
      image: prom/prometheus
      container_name: prometheus
      ports:
      - "9090:9090"
      volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules.yml:/etc/prometheus/rules.yml


  grafana:
    image: grafana/grafana:latest
    container_name: grafana-1
    ports:
      - "3000:3000"

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager-1
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/config.yml:/etc/alertmanager/config.yml:ro

volumes:
  postgres-data:
