global:
  scrape_interval: 5s

rule_files:
  - /etc/prometheus/rules.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'ai_app'
    static_configs:
      - targets: ['ai_app:8000']
